apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-platform

secretGenerator:
  - name: ca.auth
    envs:
      - example-ca-auth-key

configMapGenerator:
  - name: ca.config
    envs:
      - example-ca-config
  - name: cockroach.backup.config
    envs:
      - example-backup-config

resources:
  - base
