apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  template:
    metadata:
      annotations:
        injector.tumblr.com/request: vault-sidecar-aws
    spec:
      containers:
        - name: cockroachdb
          resources:
            requests:
              cpu: 0
              memory: "1Gi"
            limits:
              cpu: 4
              memory: "2Gi"
          env:
            - name: CACHE
              values: 256MB
            - name: MAX_SQL_MEMORY
              values: 256MB
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 50Gi
