apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
        - name: cockroachdb
          resources:
            requests:
              cpu: 0.5
              memory: "2Gi"
            limits:
              cpu: 2
              memory: "4Gi"
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
