apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - github.com/utilitywarehouse/cockroachdb-manifests//base?ref=v23.2.2-1

patchesStrategicMerge:
  - cockroach.yaml

secretGenerator:
  - name: ca-certs
    files:
      - secrets/ca.key
      - secrets/ca.crt
  - name: cockroachdb.client.root
    files:
      - secrets/client.root.key
      - secrets/client.root.crt
      - secrets/ca.crt
  - name: cockroachdb.node
    files:
      - secrets/node.key
      - secrets/node.crt
      - secrets/ca.crt

configMapGenerator:
  - name: cockroach
    envs:
      - config/cockroach
  - name: cockroach.backup.config
    envs:
      - config/backup-config
