apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-client
spec:
  template:
    spec:
      initContainers:
        - name: init-certs
          env:
          - name: CA_AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: ca.auth.keys
                key: cluster1.auth.key
      containers:
        - name: cockroachdb-client
          env:
          - name: COCKROACH_HOST
            valueFrom:
              configMapKeyRef:
                name: cockroach
                key: cockroach.host
          - name: COCKROACH_PORT
            valueFrom:
              configMapKeyRef:
                name: cockroach
                key: cockroach.port
        - name: certs-refresh
          env:
          - name: CA_AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: ca.auth.keys
                key: cluster1.auth.key
