apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
  annotations:
    "app.uw.systems/description": "Used to store data projections of events in multiple services."
    "app.uw.systems/tier": "tier_1"
    "app.uw.systems/repos.cockroachdb-manifests": "https://github.com/utilitywarehouse/cockroachdb-manifests"
    "app.uw.systems/tags.oss": "true"
spec:
  serviceName: cockroachdb
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
        policy.semaphore.uw.io/name: cockroachdb
    spec:
      serviceAccountName: cockroachdb
      shareProcessNamespace: true
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cockroachdb
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-certs
          image: cockroach-cfssl-certs
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - >
              cockroach-certs
              --host=localhost
              --host=127.0.0.1
              --host=$(hostname -f)
              --host=$(hostname -f|cut -f 1-2 -d '.')
              --host=$(COCKROACH_HOST)
              --host=$(COCKROACH_HOST).$(hostname -f|cut -f 3- -d '.')
          env:
            - name: CERTIFICATE_TYPE
              value: "node"
            - name: CERTS_DIR
              value: "/cockroach-certs"
            - name: CA_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: ca.config
                  key: ca.node.profile
            - name: CA_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ca.config
                  key: ca.endpoint
            - name: CA_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: ca.auth
                  key: key
            - name: COCKROACH_HOST
              valueFrom:
                configMapKeyRef:
                  name: cockroach
                  key: cockroach.host
          volumeMounts:
            - name: certs
              mountPath: /cockroach-certs
      containers:
        - name: cockroachdb
          image: cockroachdb
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-ecx"
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.
            - >
              exec /cockroach/cockroach start
              --logtostderr=WARNING
              --certs-dir /cockroach/cockroach-certs
              --listen-addr=:26357
              --sql-addr=:26257
              --advertise-addr $(hostname -f)
              --http-addr 0.0.0.0
              --join $(COCKROACH_JOIN_STRING)
              --cache $(CACHE)
              --max-sql-memory $(MAX_SQL_MEMORY)
          env:
            - name: COCKROACH_CHANNEL
              value: kubernetes-secure
            - name: COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING
              value: "true"
            - name: CACHE
              value: 256MB
            - name: MAX_SQL_MEMORY
              value: 256MB
            - name: COCKROACH_JOIN_STRING
              value: cockroachdb-0.cockroachdb:26257,cockroachdb-0.cockroachdb:26357,cockroachdb-1.cockroachdb:26257,cockroachdb-1.cockroachdb:26357,cockroachdb-2.cockroachdb:26257,cockroachdb-2.cockroachdb:26357
          ports:
            - containerPort: 26257
              name: sql
            - containerPort: 26357
              name: rpc
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: "/health"
              port: http
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health?ready=1"
              port: http
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 2
          volumeMounts:
            - name: datadir
              mountPath: /cockroach/cockroach-data
            - name: certs
              mountPath: /cockroach/cockroach-certs
          resources:
            requests:
              cpu: "0m"
              memory: "768Mi"
            limits:
              cpu: "4000m"
              memory: "1Gi"
        - name: certs-refresh
          image: cockroach-cfssl-certs
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - >
              cockroach-certs
              --host=localhost
              --host=127.0.0.1
              --host=$(hostname -f)
              --host=$(hostname -f|cut -f 1-2 -d '.')
              --host=$(COCKROACH_HOST)
              --host=$(COCKROACH_HOST).$(hostname -f|cut -f 3- -d '.')
              refresh-and-forward
          env:
            - name: HTTP_PORT
              value: "8001"
            - name: FORWARD_HOST
              value: "localhost:8080"
            - name: FORWARD_TIMEOUT
              value: "4s"
            - name: EXTRA_TIME
              value: "60m"
            - name: CERTIFICATE_TYPE
              value: "node"
            - name: CERTS_DIR
              value: "/cockroach-certs"
            - name: CA_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: ca.config
                  key: ca.node.profile
            - name: CA_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ca.config
                  key: ca.endpoint
            - name: CA_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: ca.auth
                  key: key
            - name: COCKROACH_HOST
              valueFrom:
                configMapKeyRef:
                  name: cockroach
                  key: cockroach.host
          volumeMounts:
            - name: certs
              mountPath: /cockroach-certs
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - containerPort: 8001
              name: http
          livenessProbe:
            httpGet:
              path: "/health"
              port: http
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 30
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: certs
          emptyDir: {}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
